### ISSUE TITLE
Compatibility for Downpour

### ISSUE THREAD

**Issue by ghost** [LeeMoriya/Downpour#3]
Is there anyway to make it compatible with Downpour easily on the user's end, or does it just need to be completely updated? I'd love to see it ported to the Steam Workshop regardless -- thanks for your hard work.

**Comment by LeeMoriya** [comment]
The mod would need to be updated to work with Downpour, which will happen eventually. Unfortunately I'm quite busy with post-release support for Expedition, so it might be a while.

**Comment by ghost** [comment]
Appreciate the reply, and good luck. Love what you've done with the Forecast mod and how it adds to the game, so I just wanted to reach out to see what your plans were.
