### ISSUE TITLE
Downpour DLC compatibility?

### ISSUE THREAD

**Issue by creidhne-a16i** [LeeMoriya/Downpour#4]
The game recently got a new DLC which bakes in mod support (based on BepInEx). There are some resources at https://rainworldmodding.miraheze.org/wiki/Downpour_Reference but I've also read that game dev are actively helping modders port their mods to the new system. Would it be possible for you to look into it?
Thanks!

**Comment by LeeMoriya** [comment]
Hi Creidhne, I am the lead developer for the Expedition mode in the new DLC, which is my main focus at the moment.
I plan to port most of my mods to Downpour, including this one but it might be a little while.

Thanks for your interest
-LeeMoriya
